//! https://projecteuler.net/problem=2
//!
//! Each new term in the Fibonacci sequence is generated by adding the
//! previous two terms. By starting with 1 and 2, the first 10 terms will be:
//!
//! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//!
//! By considering the terms in the Fibonacci sequence whose values do not
//! exceed four million, find the sum of the even-valued terms.

/// # Examples
///
/// ```
/// assert_eq!(p002::f(9), 10);
/// assert_eq!(p002::f(4000000), 4613732);
/// ```
///
pub fn f(n: i32) -> i32 {
    let mut i: i32 = 1;
    let mut j: i32 = 2;
    let mut aux: i32;
    let mut sum: i32 = j;

    while j < n {
        aux = j;
        j = i + j;
        i = aux;

        if j % 2 == 0 {
            sum = sum + j;
        }
    }
    sum
}
